### ISSUE TITLE
(Д) Нарисовать схему текущего пайплайна с эндпоинтами

### ISSUE THREAD

**Issue by zilov** [zilov/hifiblender-nf#2]
Нужно прочитать и понять код пайплайна, нарисовать схему в Miro или в Figma, ссылку на проект сюда в комменты

Сюда же прописать какие тестовые данные уже есть и каких не хватает (возможно для каких-то тулов)

**Comment by SchwarzerWolf** [comment]
https://miro.com/app/board/uXjVL8kUcJo=/?share_link_id=660409661709

**Comment by SchwarzerWolf** [comment]
Актуальная диаграмма: https://lucid.app/lucidchart/1dc2b32d-b3ff-4ed7-a17a-50513f673deb/edit?viewport_loc=-269%2C-322%2C4060%2C2288%2C0_0&invitationId=inv_c143ad64-ea87-4c35-a82d-27795a308f5f

**Comment by SchwarzerWolf** [comment]
TBA: 

- [ ] Нарисовать диаграмму потоков 
- [ ] Отметить входные данные 
- [ ] Отметить тулы, которые сейчас не работают

**Comment by SchwarzerWolf** [comment]
General диаграмма тут https://lucid.app/lucidchart/e7de62ba-1358-4f16-82fb-d3a5510f6e50/edit?viewport_loc=-188%2C-333%2C1878%2C994%2C0_0&invitationId=inv_06092d87-03aa-49f0-b61f-b097062a7448
После этого поменяла тулу из-за ограничений бесплатного аккаунта
